hyperparameters:
  seed: 228
  model_id: microsoft/deberta-v3-xsmall
  lr: 1e-4
  batch_size: 32
  num_epochs: 5
  output_dir: models/financial_tweets_sentiment_model_v2
  train_log_dir: ./runs
  weight_decay: 0.01
  eval_strategy: epoch
  save_strategy: epoch

dataset:
  train_set_path: data/processed/train
  val_set_path: data/processed/val
